include:
  - gitlab/pre.yaml
  - gitlab/pre-build-checks.yaml
  - gitlab/build.yaml
  - gitlab/post-build-checks.yaml
  - gitlab/deploy.yaml

stages:
  - .pre
  - pre-build-checks
  - build
  - post-build-checks 
  - deploy
  - .post

image: registry.access.redhat.com/ubi8/python-38

before_script:
  - env
  - ls -la /opt/app-root/lib/python3.8/site-packages/
  #- ls .cache/pip/

after_script:
  - env
  - ls -la /opt/app-root/lib/python3.8/site-packages/
  - ls .cache/pip/

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /opt/app-root/lib/python3.8/site-packages/
    - .cache/pip/

