include:
  - gitlab/templates.yaml
  - gitlab/development-container.yaml
  - gitlab/development-checks.yaml
  - gitlab/production-container.yaml
  - gitlab/production-checks.yaml
  - gitlab/deploy.yaml

stages:
  - development-container
  - development-checks
  - production-container
  - production-checks
  - deploy

variables:
  APP_DIR: /usr/src/app/
  DEVELOPMENT_CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:development
  GIT_STRATEGY: none
  PRODUCTION_CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:latest
  ARTIFACTS_DIR: artifacts/
  ARTIFACT_SOURCE_DIR: ${APP_DIR}/${ARTIFACTS_DIR}/
  ARTIFACT_DESTINATION_DIR: ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/
  SECRET_KEY: hz*n3+7658l609cz-n$zl$ly+z^@8=*2!)qh*#c2r_pzavzt3s
  DEBUG: "True"

