include:
  - gitlab/pre.yaml
  - gitlab/pre-build-checks.yaml
  - gitlab/build.yaml
  - gitlab/post-build-checks.yaml
  - gitlab/deploy.yaml

stages:
  - .pre
  - pre-build-checks
  - build
  - post-build-checks 
  - deploy
  - .post

image: registry.access.redhat.com/ubi8/python-38

before_script:
  - env
  - docker info

after_script:
  - env

variables:
  PYTHONUSERBASE: "$CI_PROJECT_DIR/.cache/pip/"
  PYTHONPATH: "$CI_PROJECT_DIR/.cache/pip/"
  PIP_TARGET: "$CI_PROJECT_DIR/.cache/pip/"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip/

