image: registry.access.redhat.com/ubi8/python-38

stages:
  - .pre
  - pre-build-checks
  - build
  - post-build-checks 
  - deploy
  - .post

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /opt/app-root/lib/python3.8/site-packages/

before_script:
  - env

include:
  - gitlab/pre.yaml
  - gitlab/pre-build-checks.yaml

