include:
  - gitlab/pre.yaml
  - gitlab/pre-build-checks.yaml
  - gitlab/build.yaml
  - gitlab/post-build-checks.yaml
  - gitlab/deploy.yaml

stages:
  - .pre
  - pre-build-checks
  - build
  - post-build-checks 
  - deploy
  - .post

#image: registry.access.redhat.com/ubi8/python-38
image: docker:19.03.12
services:
  - docker:19.03.12-dind

variables:
  #DOCKER_HOST: tcp://docker:2376
  #DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - env
  - docker info

after_script:
  - env

variables:
  PYTHONUSERBASE: "$CI_PROJECT_DIR/.cache/pip/"
  PYTHONPATH: "$CI_PROJECT_DIR/.cache/pip/"
  PIP_TARGET: "$CI_PROJECT_DIR/.cache/pip/"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip/

