x-app-override:
  &app-override
  env_file:
    - .env
    - app.env
    - database/.env
  volumes:
    - .:${APP_DIR}/

x-database-base:
  &database-base
  env_file:
    - database/.env

services:
  backend:
    <<: *app-override
    ports:
      - 8000:${APP_PORT}

  backend-production:
    <<: *app-override
    ports:
      - 8001:${APP_PORT}

  database:
    <<: *database-base

