version: '3.4'

# using extension fields is overkill in this scenario,
# but it can be useful if you need multiple similar
# instances of the same service
x-app-base:
  &app-base
  build:
    context: .
    args:
      - APP_DIR=${APP_DIR}
  command:
    - scripts/start_app.sh
  env_file:
    - .env
    - app.env
  ports:
    - ${APP_PORT}

services:
  app:
    <<: *app-base

  app-production:
    <<: *app-base

