x-app-override:
  &app-override
  env_file:
    - .env
    - app.env
    - database/.env
  volumes:
    - .:${APP_DIR}/

x-database-base:
  &database-base
  env_file:
    - database/.env

services:
  backend:
    <<: *app-override
    ports:
      - 8000:${APP_PORT}

  backend-production:
    <<: *app-override
    ports:
      - 8001:${APP_PORT}
    deploy:
      replicas: 0

  database:
    <<: *database-base

  shell-checker:
    image: koalaman/shellcheck-alpine:v0.7.1
    working_dir: /mnt/
    command:
      - scripts/lint_app/run_shellcheck.sh
    volumes:
      - .:/mnt/
    deploy:
      replicas: 0 # run as one-off process not part of doker-compose up

