x-app-base:
  &app-base
  build: &app-build-base
    context: .
    args:
      - APP_DIR=${APP_DIR}
  command:
    - scripts/start_app.sh
  ports:
    - ${APP_PORT}
  depends_on:
    - database
  env_file:
    - .env
    - app.env
    - database/.env

x-database-base:
  &database-base
  image: postgres:13.0
  env_file:
    - database/.env
  volumes:
    - data:/var/lib/postgresql/data/

services:
  backend:
    <<: *app-base
    build:
      <<: *app-build-base
      target: development

  backend-production:
    <<: *app-base
    build:
      <<: *app-build-base
      target: production
    environment:
      - DEBUG=False

  database:
    <<: *database-base

volumes:
  data:

