version: '3.4'

x-app-override:
  &app-override
  volumes:
    - .:${APP_DIR}/

services:
  app:
    <<: *app-override
    build:
      target: development
    ports:
      - ${APP_PORT}:${APP_PORT}

  app-production:
    <<: *app-override
    ports:
      - 8001:${APP_PORT}

