x-app-override:
  &app-override
  volumes:
    - ${BACKEND_BASE:-.}:${APP_DIR}/

services:
  backend:
    <<: *app-override
    ports:
      - 8000:${APP_PORT}

  backend-production:
    <<: *app-override
    ports:
      - 8001:${APP_PORT}
    deploy:
      replicas: 0

  shell-checker:
    image: koalaman/shellcheck-alpine:v0.7.1
    working_dir: /mnt/
    command:
      - scripts/lint_app/run_shellcheck.sh
    volumes:
      - ${BACKEND_BASE:-.}:/mnt/
    deploy:
      replicas: 0

