version: '3.4'

x-app-base:
  &app-base
  build:
    context: .
    args:
      - APP_DIR=${APP_DIR}
  command:
    - scripts/start_app.sh
  ports:
    - ${APP_PORT}
  depends_on:
    - database

x-database-base:
  &database-base
  image: postgres:13.0
  volumes:
    - data:/var/lib/postgresql/data/

services:
  backend:
    <<: *app-base
    build:
      target: development

  backend-production:
    <<: *app-base
    build:
      target: production

  database:
    <<: *database-base

volumes:
  data:

