version: '3.4'

x-app-base:
  &app-base
  build:
    context: .
    args:
      - APP_DIR=${APP_DIR}
  command:
    - scripts/start_app.sh
  env_file:
    - .env
    - app.env
    - database/.env
  ports:
    - ${APP_PORT}
  depends_on:
    - database

x-database-base:
  &database-base
  image: postgres:13.0
  env_file:
    - database/.env
  volumes:
    - data:/var/lib/postgresql/data/

services:
  app:
    <<: *app-base

  app-production:
    <<: *app-base

  database:
    <<: *database-base

volumes:
  data:

