.base:
  &base
  stage: production-checks
  image: $PRODUCTION_CONTAINER_IMAGE
  extends: .common

integration-test:
  <<: *base
  script:
    - echo "production container specific testing is yet to come"

