.base:
  &base
  needs:
    - build-production-container
  stage: production-checks
  image: $PRODUCTION_CONTAINER_IMAGE

integration-test:
  <<: *base
  extends:
    - .database
    - .cache-coverage
  needs:
    - build-production-container
    - unit-test
  before_script:
    - cd $APP_DIR
    - pip install
        coverage
        factory_boy
        unittest-xml-reporting
    - cp $CI_PROJECT_DIR/.coverage $APP_DIR/.
  script:
    - scripts/test_app/run_integration_tests.sh
    - coverage xml
    - coverage report
  after_script:
    - cp $APP_DIR/coverage.xml $CI_PROJECT_DIR/.
    - cp $APP_DIR/test.xml $CI_PROJECT_DIR/.
  cache:
    policy: pull
  artifacts:
    reports:
      cobertura: coverage.xml
      junit: test.xml

