.base:
  &base
  stage: production-checks
  image: $PRODUCTION_CONTAINER_IMAGE

production-unit-test:
  <<: *base
  extends: .unit-test
  allow_failure: true
  scripts:
    - echo "coverage is not installed for production image"

