.base:
  &base
  needs:
    - build-production-container
  stage: production-checks
  image: ${PRODUCTION_CONTAINER_IMAGE}
  before_script:
    - cd ${APP_DIR}
    - ls -la

integration-test:
  <<: *base
  needs:
    - build-production-container
    - unit-test
  extends:
    - .database
    - .cache-coverage
  before_script:
    - cd ${APP_DIR}
    - pip install
        coverage
        factory_boy
        unittest-xml-reporting
    - cp ${ARTIFACT_DESTINATION_DIR}/.coverage ${ARTIFACT_SOURCE_DIR}/
  script:
    - scripts/test_app/run_integration_tests.sh
    - coverage report --fail-under=100
  after_script:
    - coverage xml
    - cp --recursive ${ARTIFACT_SOURCE_DIR}/ ${CI_PROJECT_DIR}/
  artifacts:
    reports:
      junit: ${ARTIFACT_DESTINATION_DIR}/test.xml
      coverage_reports:
        coverage_format: cobertura
        path: ${ARTIFACT_DESTINATION_DIR}/coverage.xml

