.base:
  &base
  extends: .common
  stage: production-checks
  image: $PRODUCTION_CONTAINER_IMAGE
  needs:
    - build-production-container

integration-test:
  <<: *base
  script:
    - echo "production container specific testing is yet to come"

