.base:
  &base
  extends: .common
  stage: production-checks
  image: $PRODUCTION_CONTAINER_IMAGE

integration-test:
  <<: *base
  script:
    - echo "production container specific testing is yet to come"

